[2021-04-27 17:59:22,745] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: docker_sample.sleep 2021-04-25T06:00:00+00:00 [queued]>
[2021-04-27 17:59:22,778] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: docker_sample.sleep 2021-04-25T06:00:00+00:00 [queued]>
[2021-04-27 17:59:22,780] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-04-27 17:59:22,781] {taskinstance.py:1043} INFO - Starting attempt 1 of 4
[2021-04-27 17:59:22,783] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-04-27 17:59:22,808] {taskinstance.py:1063} INFO - Executing <Task(BashOperator): sleep> on 2021-04-25T06:00:00+00:00
[2021-04-27 17:59:22,817] {standard_task_runner.py:52} INFO - Started process 440 to run task
[2021-04-27 17:59:22,836] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'docker_sample', 'sleep', '2021-04-25T06:00:00+00:00', '--job-id', '147', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dockerOperator.py', '--cfg-path', '/tmp/tmp7sfvfvmd', '--error-file', '/tmp/tmp6w2t3xzd']
[2021-04-27 17:59:22,838] {standard_task_runner.py:77} INFO - Job 147: Subtask sleep
[2021-04-27 17:59:22,920] {logging_mixin.py:104} INFO - Running <TaskInstance: docker_sample.sleep 2021-04-25T06:00:00+00:00 [running]> on host 44e91a58ae1b
[2021-04-27 17:59:22,982] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=airflow@example.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=docker_sample
AIRFLOW_CTX_TASK_ID=sleep
AIRFLOW_CTX_EXECUTION_DATE=2021-04-25T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-04-25T06:00:00+00:00
[2021-04-27 17:59:22,984] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2021-04-27 17:59:22,986] {bash.py:158} INFO - Running command: sleep 5
[2021-04-27 17:59:23,001] {bash.py:169} INFO - Output:
[2021-04-27 17:59:28,006] {bash.py:177} INFO - Command exited with return code 0
[2021-04-27 17:59:28,036] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=docker_sample, task_id=sleep, execution_date=20210425T060000, start_date=20210427T175922, end_date=20210427T175928
[2021-04-27 17:59:28,069] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-04-27 17:59:28,104] {local_task_job.py:146} INFO - Task exited with return code 0
