[2021-04-27 17:57:39,499] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: docker_sample.docker_op_tester 2021-04-25T02:10:00+00:00 [queued]>
[2021-04-27 17:57:39,513] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: docker_sample.docker_op_tester 2021-04-25T02:10:00+00:00 [queued]>
[2021-04-27 17:57:39,514] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-04-27 17:57:39,515] {taskinstance.py:1043} INFO - Starting attempt 1 of 2
[2021-04-27 17:57:39,515] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-04-27 17:57:39,523] {taskinstance.py:1063} INFO - Executing <Task(DockerOperator): docker_op_tester> on 2021-04-25T02:10:00+00:00
[2021-04-27 17:57:39,528] {standard_task_runner.py:52} INFO - Started process 133 to run task
[2021-04-27 17:57:39,532] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'docker_sample', 'docker_op_tester', '2021-04-25T02:10:00+00:00', '--job-id', '36', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dockerOperator.py', '--cfg-path', '/tmp/tmpe1svncfq', '--error-file', '/tmp/tmp9q7t4k7p']
[2021-04-27 17:57:39,533] {standard_task_runner.py:77} INFO - Job 36: Subtask docker_op_tester
[2021-04-27 17:57:39,577] {logging_mixin.py:104} INFO - Running <TaskInstance: docker_sample.docker_op_tester 2021-04-25T02:10:00+00:00 [running]> on host 44e91a58ae1b
[2021-04-27 17:57:39,617] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=airflow@example.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=docker_sample
AIRFLOW_CTX_TASK_ID=docker_op_tester
AIRFLOW_CTX_EXECUTION_DATE=2021-04-25T02:10:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-04-25T02:10:00+00:00
[2021-04-27 17:57:39,630] {docker.py:224} INFO - Starting docker container from image centos:latest
[2021-04-27 17:58:10,105] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=docker_sample, task_id=docker_op_tester, execution_date=20210425T021000, start_date=20210427T175739, end_date=20210427T175810
[2021-04-27 17:58:10,155] {taskinstance.py:1220} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-04-27 17:58:10,202] {local_task_job.py:146} INFO - Task exited with return code 0
