[2021-04-23 11:26:26,629] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: docker_sample.sleep 2021-04-21T00:20:00+00:00 [queued]>
[2021-04-23 11:26:26,685] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: docker_sample.sleep 2021-04-21T00:20:00+00:00 [queued]>
[2021-04-23 11:26:26,688] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-04-23 11:26:26,692] {taskinstance.py:1043} INFO - Starting attempt 1 of 4
[2021-04-23 11:26:26,696] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-04-23 11:26:26,712] {taskinstance.py:1063} INFO - Executing <Task(BashOperator): sleep> on 2021-04-21T00:20:00+00:00
[2021-04-23 11:26:26,718] {standard_task_runner.py:52} INFO - Started process 137 to run task
[2021-04-23 11:26:26,743] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'docker_sample', 'sleep', '2021-04-21T00:20:00+00:00', '--job-id', '766', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dockerOperator.py', '--cfg-path', '/tmp/tmp6s88lrft', '--error-file', '/tmp/tmp9c7ajhiu']
[2021-04-23 11:26:26,748] {standard_task_runner.py:77} INFO - Job 766: Subtask sleep
[2021-04-23 11:26:26,853] {logging_mixin.py:104} INFO - Running <TaskInstance: docker_sample.sleep 2021-04-21T00:20:00+00:00 [running]> on host 5af2b1cab26e
[2021-04-23 11:26:26,949] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=airflow@example.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=docker_sample
AIRFLOW_CTX_TASK_ID=sleep
AIRFLOW_CTX_EXECUTION_DATE=2021-04-21T00:20:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-04-21T00:20:00+00:00
[2021-04-23 11:26:26,953] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2021-04-23 11:26:26,957] {bash.py:158} INFO - Running command: sleep 5
[2021-04-23 11:26:26,974] {bash.py:169} INFO - Output:
[2021-04-23 11:26:32,004] {bash.py:177} INFO - Command exited with return code 0
[2021-04-23 11:26:32,033] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=docker_sample, task_id=sleep, execution_date=20210421T002000, start_date=20210423T112626, end_date=20210423T112632
[2021-04-23 11:26:32,060] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-04-23 11:26:32,085] {local_task_job.py:146} INFO - Task exited with return code 0
