[2021-04-27 17:57:34,400] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: docker_sample.docker_op_tester 2021-04-25T01:10:00+00:00 [queued]>
[2021-04-27 17:57:34,440] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: docker_sample.docker_op_tester 2021-04-25T01:10:00+00:00 [queued]>
[2021-04-27 17:57:34,441] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-04-27 17:57:34,442] {taskinstance.py:1043} INFO - Starting attempt 1 of 2
[2021-04-27 17:57:34,443] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-04-27 17:57:34,455] {taskinstance.py:1063} INFO - Executing <Task(DockerOperator): docker_op_tester> on 2021-04-25T01:10:00+00:00
[2021-04-27 17:57:34,461] {standard_task_runner.py:52} INFO - Started process 109 to run task
[2021-04-27 17:57:34,467] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'docker_sample', 'docker_op_tester', '2021-04-25T01:10:00+00:00', '--job-id', '25', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dockerOperator.py', '--cfg-path', '/tmp/tmptya4r7z_', '--error-file', '/tmp/tmpyqfjcosa']
[2021-04-27 17:57:34,471] {standard_task_runner.py:77} INFO - Job 25: Subtask docker_op_tester
[2021-04-27 17:57:34,545] {logging_mixin.py:104} INFO - Running <TaskInstance: docker_sample.docker_op_tester 2021-04-25T01:10:00+00:00 [running]> on host 44e91a58ae1b
[2021-04-27 17:57:34,596] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=airflow@example.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=docker_sample
AIRFLOW_CTX_TASK_ID=docker_op_tester
AIRFLOW_CTX_EXECUTION_DATE=2021-04-25T01:10:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-04-25T01:10:00+00:00
[2021-04-27 17:57:34,610] {docker.py:224} INFO - Starting docker container from image centos:latest
[2021-04-27 17:58:05,662] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=docker_sample, task_id=docker_op_tester, execution_date=20210425T011000, start_date=20210427T175734, end_date=20210427T175805
[2021-04-27 17:58:05,709] {taskinstance.py:1220} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-04-27 17:58:05,756] {local_task_job.py:146} INFO - Task exited with return code 0
