[2021-04-21 20:15:06,723] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: docker_sample.sleep 2021-04-19T06:20:00+00:00 [queued]>
[2021-04-21 20:15:06,763] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: docker_sample.sleep 2021-04-19T06:20:00+00:00 [queued]>
[2021-04-21 20:15:06,767] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-04-21 20:15:06,768] {taskinstance.py:1043} INFO - Starting attempt 1 of 4
[2021-04-21 20:15:06,769] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-04-21 20:15:06,797] {taskinstance.py:1063} INFO - Executing <Task(BashOperator): sleep> on 2021-04-19T06:20:00+00:00
[2021-04-21 20:15:06,804] {standard_task_runner.py:52} INFO - Started process 501 to run task
[2021-04-21 20:15:06,816] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'docker_sample', 'sleep', '2021-04-19T06:20:00+00:00', '--job-id', '220', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dockerOperator.py', '--cfg-path', '/tmp/tmpkdv01hg7', '--error-file', '/tmp/tmp6ueo7x1l']
[2021-04-21 20:15:06,818] {standard_task_runner.py:77} INFO - Job 220: Subtask sleep
[2021-04-21 20:15:06,913] {logging_mixin.py:104} INFO - Running <TaskInstance: docker_sample.sleep 2021-04-19T06:20:00+00:00 [running]> on host 5af2b1cab26e
[2021-04-21 20:15:07,011] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=airflow@example.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=docker_sample
AIRFLOW_CTX_TASK_ID=sleep
AIRFLOW_CTX_EXECUTION_DATE=2021-04-19T06:20:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-04-19T06:20:00+00:00
[2021-04-21 20:15:07,013] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2021-04-21 20:15:07,015] {bash.py:158} INFO - Running command: sleep 5
[2021-04-21 20:15:07,048] {bash.py:169} INFO - Output:
[2021-04-21 20:15:12,052] {bash.py:177} INFO - Command exited with return code 0
[2021-04-21 20:15:12,097] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=docker_sample, task_id=sleep, execution_date=20210419T062000, start_date=20210421T201506, end_date=20210421T201512
[2021-04-21 20:15:12,134] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-04-21 20:15:12,189] {local_task_job.py:146} INFO - Task exited with return code 0
