[2021-04-21 20:16:12,487] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: docker_sample.sleep 2021-04-19T10:30:00+00:00 [queued]>
[2021-04-21 20:16:12,530] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: docker_sample.sleep 2021-04-19T10:30:00+00:00 [queued]>
[2021-04-21 20:16:12,536] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-04-21 20:16:12,539] {taskinstance.py:1043} INFO - Starting attempt 1 of 4
[2021-04-21 20:16:12,542] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-04-21 20:16:12,566] {taskinstance.py:1063} INFO - Executing <Task(BashOperator): sleep> on 2021-04-19T10:30:00+00:00
[2021-04-21 20:16:12,575] {standard_task_runner.py:52} INFO - Started process 724 to run task
[2021-04-21 20:16:12,594] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'docker_sample', 'sleep', '2021-04-19T10:30:00+00:00', '--job-id', '300', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dockerOperator.py', '--cfg-path', '/tmp/tmplj5nu8iz', '--error-file', '/tmp/tmpsjcuev2k']
[2021-04-21 20:16:12,598] {standard_task_runner.py:77} INFO - Job 300: Subtask sleep
[2021-04-21 20:16:12,799] {logging_mixin.py:104} INFO - Running <TaskInstance: docker_sample.sleep 2021-04-19T10:30:00+00:00 [running]> on host 5af2b1cab26e
[2021-04-21 20:16:13,129] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=airflow@example.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=docker_sample
AIRFLOW_CTX_TASK_ID=sleep
AIRFLOW_CTX_EXECUTION_DATE=2021-04-19T10:30:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-04-19T10:30:00+00:00
[2021-04-21 20:16:13,134] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2021-04-21 20:16:13,143] {bash.py:158} INFO - Running command: sleep 5
[2021-04-21 20:16:13,196] {bash.py:169} INFO - Output:
[2021-04-21 20:16:18,199] {bash.py:177} INFO - Command exited with return code 0
[2021-04-21 20:16:18,225] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=docker_sample, task_id=sleep, execution_date=20210419T103000, start_date=20210421T201612, end_date=20210421T201618
[2021-04-21 20:16:18,248] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-04-21 20:16:18,290] {local_task_job.py:146} INFO - Task exited with return code 0
