[2021-04-21 20:17:47,819] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: docker_sample.docker_op_tester 2021-04-19T15:50:00+00:00 [queued]>
[2021-04-21 20:17:47,832] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: docker_sample.docker_op_tester 2021-04-19T15:50:00+00:00 [queued]>
[2021-04-21 20:17:47,833] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-04-21 20:17:47,834] {taskinstance.py:1043} INFO - Starting attempt 1 of 2
[2021-04-21 20:17:47,835] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-04-21 20:17:47,840] {taskinstance.py:1063} INFO - Executing <Task(DockerOperator): docker_op_tester> on 2021-04-19T15:50:00+00:00
[2021-04-21 20:17:47,844] {standard_task_runner.py:52} INFO - Started process 1020 to run task
[2021-04-21 20:17:47,847] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'docker_sample', 'docker_op_tester', '2021-04-19T15:50:00+00:00', '--job-id', '409', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dockerOperator.py', '--cfg-path', '/tmp/tmpi5c2crvm', '--error-file', '/tmp/tmpmg4mim_1']
[2021-04-21 20:17:47,849] {standard_task_runner.py:77} INFO - Job 409: Subtask docker_op_tester
[2021-04-21 20:17:47,887] {logging_mixin.py:104} INFO - Running <TaskInstance: docker_sample.docker_op_tester 2021-04-19T15:50:00+00:00 [running]> on host 5af2b1cab26e
[2021-04-21 20:17:47,920] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=airflow@example.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=docker_sample
AIRFLOW_CTX_TASK_ID=docker_op_tester
AIRFLOW_CTX_EXECUTION_DATE=2021-04-19T15:50:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-04-19T15:50:00+00:00
[2021-04-21 20:17:47,929] {docker.py:224} INFO - Starting docker container from image centos:latest
[2021-04-21 20:18:18,365] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=docker_sample, task_id=docker_op_tester, execution_date=20210419T155000, start_date=20210421T201747, end_date=20210421T201818
[2021-04-21 20:18:18,397] {taskinstance.py:1220} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-04-21 20:18:18,435] {local_task_job.py:146} INFO - Task exited with return code 0
