[2021-04-21 20:13:34,674] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: docker_sample.sleep 2021-04-19T03:20:00+00:00 [queued]>
[2021-04-21 20:13:34,735] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: docker_sample.sleep 2021-04-19T03:20:00+00:00 [queued]>
[2021-04-21 20:13:34,736] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-04-21 20:13:34,738] {taskinstance.py:1043} INFO - Starting attempt 1 of 4
[2021-04-21 20:13:34,739] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-04-21 20:13:34,768] {taskinstance.py:1063} INFO - Executing <Task(BashOperator): sleep> on 2021-04-19T03:20:00+00:00
[2021-04-21 20:13:34,776] {standard_task_runner.py:52} INFO - Started process 268 to run task
[2021-04-21 20:13:34,789] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'docker_sample', 'sleep', '2021-04-19T03:20:00+00:00', '--job-id', '134', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dockerOperator.py', '--cfg-path', '/tmp/tmprk_mqepi', '--error-file', '/tmp/tmp0bqno1hk']
[2021-04-21 20:13:34,790] {standard_task_runner.py:77} INFO - Job 134: Subtask sleep
[2021-04-21 20:13:34,903] {logging_mixin.py:104} INFO - Running <TaskInstance: docker_sample.sleep 2021-04-19T03:20:00+00:00 [running]> on host 5af2b1cab26e
[2021-04-21 20:13:34,984] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=airflow@example.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=docker_sample
AIRFLOW_CTX_TASK_ID=sleep
AIRFLOW_CTX_EXECUTION_DATE=2021-04-19T03:20:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-04-19T03:20:00+00:00
[2021-04-21 20:13:34,986] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2021-04-21 20:13:34,989] {bash.py:158} INFO - Running command: sleep 5
[2021-04-21 20:13:35,011] {bash.py:169} INFO - Output:
[2021-04-21 20:13:40,015] {bash.py:177} INFO - Command exited with return code 0
[2021-04-21 20:13:40,104] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=docker_sample, task_id=sleep, execution_date=20210419T032000, start_date=20210421T201334, end_date=20210421T201340
[2021-04-21 20:13:40,183] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-04-21 20:13:40,208] {local_task_job.py:146} INFO - Task exited with return code 0
