[2021-04-21 20:16:41,923] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: docker_sample.docker_op_tester 2021-04-19T12:50:00+00:00 [queued]>
[2021-04-21 20:16:41,970] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: docker_sample.docker_op_tester 2021-04-19T12:50:00+00:00 [queued]>
[2021-04-21 20:16:41,971] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-04-21 20:16:41,972] {taskinstance.py:1043} INFO - Starting attempt 1 of 2
[2021-04-21 20:16:41,974] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-04-21 20:16:41,990] {taskinstance.py:1063} INFO - Executing <Task(DockerOperator): docker_op_tester> on 2021-04-19T12:50:00+00:00
[2021-04-21 20:16:41,998] {standard_task_runner.py:52} INFO - Started process 842 to run task
[2021-04-21 20:16:42,011] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'docker_sample', 'docker_op_tester', '2021-04-19T12:50:00+00:00', '--job-id', '343', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dockerOperator.py', '--cfg-path', '/tmp/tmpn8kpj4fg', '--error-file', '/tmp/tmpbd4k25gs']
[2021-04-21 20:16:42,013] {standard_task_runner.py:77} INFO - Job 343: Subtask docker_op_tester
[2021-04-21 20:16:42,126] {logging_mixin.py:104} INFO - Running <TaskInstance: docker_sample.docker_op_tester 2021-04-19T12:50:00+00:00 [running]> on host 5af2b1cab26e
[2021-04-21 20:16:42,199] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=airflow@example.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=docker_sample
AIRFLOW_CTX_TASK_ID=docker_op_tester
AIRFLOW_CTX_EXECUTION_DATE=2021-04-19T12:50:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-04-19T12:50:00+00:00
[2021-04-21 20:16:42,221] {docker.py:224} INFO - Starting docker container from image centos:latest
[2021-04-21 20:17:13,589] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=docker_sample, task_id=docker_op_tester, execution_date=20210419T125000, start_date=20210421T201641, end_date=20210421T201713
[2021-04-21 20:17:13,711] {taskinstance.py:1220} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-04-21 20:17:13,792] {local_task_job.py:146} INFO - Task exited with return code 0
