[2021-04-21 20:21:34,784] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: docker_sample.print_date 2021-04-20T00:50:00+00:00 [queued]>
[2021-04-21 20:21:34,827] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: docker_sample.print_date 2021-04-20T00:50:00+00:00 [queued]>
[2021-04-21 20:21:34,829] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-04-21 20:21:34,831] {taskinstance.py:1043} INFO - Starting attempt 1 of 2
[2021-04-21 20:21:34,833] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-04-21 20:21:34,848] {taskinstance.py:1063} INFO - Executing <Task(BashOperator): print_date> on 2021-04-20T00:50:00+00:00
[2021-04-21 20:21:34,854] {standard_task_runner.py:52} INFO - Started process 1645 to run task
[2021-04-21 20:21:34,877] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'docker_sample', 'print_date', '2021-04-20T00:50:00+00:00', '--job-id', '633', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dockerOperator.py', '--cfg-path', '/tmp/tmpct7cmqep', '--error-file', '/tmp/tmp0u_xqmjo']
[2021-04-21 20:21:34,889] {standard_task_runner.py:77} INFO - Job 633: Subtask print_date
[2021-04-21 20:21:34,974] {logging_mixin.py:104} INFO - Running <TaskInstance: docker_sample.print_date 2021-04-20T00:50:00+00:00 [running]> on host 5af2b1cab26e
[2021-04-21 20:21:35,114] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=airflow@example.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=docker_sample
AIRFLOW_CTX_TASK_ID=print_date
AIRFLOW_CTX_EXECUTION_DATE=2021-04-20T00:50:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-04-20T00:50:00+00:00
[2021-04-21 20:21:35,115] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2021-04-21 20:21:35,118] {bash.py:158} INFO - Running command: date
[2021-04-21 20:21:35,150] {bash.py:169} INFO - Output:
[2021-04-21 20:21:35,162] {bash.py:173} INFO - Wed Apr 21 20:21:35 UTC 2021
[2021-04-21 20:21:35,163] {bash.py:177} INFO - Command exited with return code 0
[2021-04-21 20:21:35,245] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=docker_sample, task_id=print_date, execution_date=20210420T005000, start_date=20210421T202134, end_date=20210421T202135
[2021-04-21 20:21:35,308] {taskinstance.py:1220} INFO - 2 downstream tasks scheduled from follow-on schedule check
[2021-04-21 20:21:35,342] {local_task_job.py:146} INFO - Task exited with return code 0
