[2021-04-27 17:57:38,356] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: docker_sample.docker_op_tester 2021-04-25T01:50:00+00:00 [queued]>
[2021-04-27 17:57:38,381] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: docker_sample.docker_op_tester 2021-04-25T01:50:00+00:00 [queued]>
[2021-04-27 17:57:38,384] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-04-27 17:57:38,385] {taskinstance.py:1043} INFO - Starting attempt 1 of 2
[2021-04-27 17:57:38,387] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-04-27 17:57:38,402] {taskinstance.py:1063} INFO - Executing <Task(DockerOperator): docker_op_tester> on 2021-04-25T01:50:00+00:00
[2021-04-27 17:57:38,415] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'docker_sample', 'docker_op_tester', '2021-04-25T01:50:00+00:00', '--job-id', '34', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dockerOperator.py', '--cfg-path', '/tmp/tmpjdv55ik4', '--error-file', '/tmp/tmpx7boglak']
[2021-04-27 17:57:38,416] {standard_task_runner.py:77} INFO - Job 34: Subtask docker_op_tester
[2021-04-27 17:57:38,407] {standard_task_runner.py:52} INFO - Started process 130 to run task
[2021-04-27 17:57:38,468] {logging_mixin.py:104} INFO - Running <TaskInstance: docker_sample.docker_op_tester 2021-04-25T01:50:00+00:00 [running]> on host 44e91a58ae1b
[2021-04-27 17:57:38,524] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=airflow@example.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=docker_sample
AIRFLOW_CTX_TASK_ID=docker_op_tester
AIRFLOW_CTX_EXECUTION_DATE=2021-04-25T01:50:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-04-25T01:50:00+00:00
[2021-04-27 17:57:38,537] {docker.py:224} INFO - Starting docker container from image centos:latest
[2021-04-27 17:58:09,075] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=docker_sample, task_id=docker_op_tester, execution_date=20210425T015000, start_date=20210427T175738, end_date=20210427T175809
[2021-04-27 17:58:09,115] {taskinstance.py:1220} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-04-27 17:58:09,172] {local_task_job.py:146} INFO - Task exited with return code 0
