[2021-04-21 20:14:34,929] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: docker_sample.sleep 2021-04-19T06:00:00+00:00 [queued]>
[2021-04-21 20:14:34,963] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: docker_sample.sleep 2021-04-19T06:00:00+00:00 [queued]>
[2021-04-21 20:14:34,964] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-04-21 20:14:34,965] {taskinstance.py:1043} INFO - Starting attempt 1 of 4
[2021-04-21 20:14:34,966] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-04-21 20:14:34,976] {taskinstance.py:1063} INFO - Executing <Task(BashOperator): sleep> on 2021-04-19T06:00:00+00:00
[2021-04-21 20:14:34,981] {standard_task_runner.py:52} INFO - Started process 440 to run task
[2021-04-21 20:14:34,993] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'docker_sample', 'sleep', '2021-04-19T06:00:00+00:00', '--job-id', '195', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dockerOperator.py', '--cfg-path', '/tmp/tmpedjdcxo6', '--error-file', '/tmp/tmpnj90qntr']
[2021-04-21 20:14:34,995] {standard_task_runner.py:77} INFO - Job 195: Subtask sleep
[2021-04-21 20:14:35,064] {logging_mixin.py:104} INFO - Running <TaskInstance: docker_sample.sleep 2021-04-19T06:00:00+00:00 [running]> on host 5af2b1cab26e
[2021-04-21 20:14:35,152] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=airflow@example.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=docker_sample
AIRFLOW_CTX_TASK_ID=sleep
AIRFLOW_CTX_EXECUTION_DATE=2021-04-19T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-04-19T06:00:00+00:00
[2021-04-21 20:14:35,153] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2021-04-21 20:14:35,155] {bash.py:158} INFO - Running command: sleep 5
[2021-04-21 20:14:35,171] {bash.py:169} INFO - Output:
[2021-04-21 20:14:40,179] {bash.py:177} INFO - Command exited with return code 0
[2021-04-21 20:14:40,248] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=docker_sample, task_id=sleep, execution_date=20210419T060000, start_date=20210421T201434, end_date=20210421T201440
[2021-04-21 20:14:40,311] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-04-21 20:14:40,340] {local_task_job.py:146} INFO - Task exited with return code 0
